### ISSUE TITLE
some probs

### ISSUE THREAD

**Issue by mikes222** [marianocordoba/fab-circular-menu#1]
1. why do you force the child parameter? seems it is not really necessary.
2. I suggest to assert required params, e.g. `FabCircularMenu(...) : assert(child != null),
        assert(options != null && options.length > 0);`
3. If you want to provide this code as a library you need to move it to the lib/src folder and provide a dart file with `export` statements. See other libs. Currently I am unable to use your code as a lib. I rather copied the source code into my own repository instead. 
4. Please add a dispose method:

```
    @override
    void dispose() {
      controller?.dispose();
      super.dispose();
    }
```
5. I still struggle when using 4 icons. In closed state the middle icons 1 and 2 are shown in the right-bottom corner beneath the fab. 

![grafik](https://user-images.githubusercontent.com/2129663/59720657-bdf37000-921f-11e9-9f8b-e83eb70a897f.png)

![grafik](https://user-images.githubusercontent.com/2129663/59720693-cc418c00-921f-11e9-925f-b9012edbe3e6.png)

You may find the problem, I don't currently. 

6. Seems it is not allowed to init the controller twice. Move that initialization to the `initState()` method instead:

```
  @override
  void initState() {
    super.initState();
    controller = AnimationController(duration: widget.animationDuration, vsync: this);
  }
```

**Comment by marianocordoba** [comment]
Thank you a lot for your feedback. This is my first package so i'm still learning. 
I will take a look asap.

**Comment by spiralni** [comment]
Beautiful widget. You must NOT initialize controller in the `didChangeDependenciesMethod()` but instead initialize it in the `initState()`. Right now I am having a problem when I open a new screen using navigator e.g

`  void _navigateToTreatment(BuildContext context) {
    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) => TreatmentFormPage(),
      )
    );
  }`

I've got this error message:

`_FabCircularMenuState is a SingleTickerProviderStateMixin but multiple tickers were created.`

and its because of the re-assigment of the controller in the `didChangeDependenciesMethod()`.

Plus, it will be interesting exposing the method to reverse the animation manually.

Thanks, and good work!

**Comment by kevinomyonga** [comment]
> Beautiful widget. You must NOT initialize controller in the `didChangeDependenciesMethod()` but instead initialize it in the `initState()`. Right now I am having a problem when I open a new screen using navigator e.g
> 
> ` void _navigateToTreatment(BuildContext context) { Navigator.of(context).push( MaterialPageRoute( builder: (context) => TreatmentFormPage(), ) ); }`
> 
> I've got this error message:
> 
> `_FabCircularMenuState is a SingleTickerProviderStateMixin but multiple tickers were created.`
> 
> and its because of the re-assigment of the controller in the `didChangeDependenciesMethod()`.
> 
> Plus, it will be interesting exposing the method to reverse the animation manually.
> 
> Thanks, and good work!

Has a solution to the aforementioned issue been found?

**Comment by marianocordoba** [comment]
Ok, i fixed the issue found by @spiralni, added an assertion and a dispose method. The `child` is still required because you are supposed to use this widget as a container, not as a `Scaffold`'s `floatingActionButton` because if you do that, you end up with a margin around the circle.
