### ISSUE TITLE
Need ringWidth, please Advise?

### ISSUE THREAD

**Issue by YohanWadia** [marianocordoba/fab-circular-menu#12]
Hi, I am trying out my project on Web too. Thats where I need the ringWidth. I see you get this from ringDiameter.. and that from screenWidth.

Is there any recommended way that I may get that present ringWidth? Besides doing the entire thing from scratch with Screen class??
Also, if there isnt, how may I know when the widget has finished its constructor, because thats the time I might try to trap the  fabKey.currentState.widget.ringDiameter value into a double variable.

thanks,
Great package by the way!

**Comment by marianocordoba** [comment]
Hi @YohanWadia! Actually, there is a [`ringWidth`](https://github.com/marianocordoba/fab-circular-menu/blob/master/lib/fab_circular_menu.dart#L14) property that you can use:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Placeholder(),
        floatingActionButton: FabCircularMenu(
          ringDiameter: 200.0,
          ringWidth: 50.0,
          children: <Widget>[
            IconButton(icon: Icon(Icons.home), onPressed: () {
              print('Home');
            }),
            IconButton(icon: Icon(Icons.favorite), onPressed: () {
              print('Favorite');
            })
          ]
        )
      )
    );
  }
}
```

**Comment by YohanWadia** [comment]
Hi,
First of all, Congratulations of a great package.
I dont think you understood my Q.

you see by default you already have got ring diameter as 
`screenWidth * 1.25`
i wanted to extract that value from your widget... rather than me re doing a
`double width = MediaQuery.of(context).size.width;`

did you get it?
How could I get it from your already set default value... only if it is possible 

thanks.
