### ISSUE TITLE
More of a Question than an issue - how to add text below the icon?

### ISSUE THREAD

**Issue by pedez** [marianocordoba/fab-circular-menu#13]
I tried to create a Column widget with the Icon and the Text widget, but then the button would be placed in a random place far away from where it was supposed to. I even tried the column as a child of the RawMaterialButton, but same result.

Is it possible to add text below the icon with this package? I would love know. Great package thanks for the content!

**Comment by fusion44** [comment]
You can use a Stack for this. I use this helper function:

```dart
  Widget _buildIconButtonWithText(
    Function onPressed,
    String text,
    String tooltip,
  ) {
    return Container(
      width: 68,
      height: 55,
      child: Stack(
        children: [
          Align(
            alignment: Alignment.bottomCenter,
            child: Text(text),
          ),
          Align(
            alignment: Alignment.topCenter,
            child: IconButton(
              icon: Icon(Icons.edit),
              onPressed: onPressed,
              tooltip: tooltip,
            ),
          ),
        ],
      ),
    );
  }
```

**Comment by pedez** [comment]
> You can use a Stack for this. I use this helper function:
> 
> ```dart
>   Widget _buildIconButtonWithText(
>     Function onPressed,
>     String text,
>     String tooltip,
>   ) {
>     return Container(
>       width: 68,
>       height: 55,
>       child: Stack(
>         children: [
>           Align(
>             alignment: Alignment.bottomCenter,
>             child: Text(text),
>           ),
>           Align(
>             alignment: Alignment.topCenter,
>             child: IconButton(
>               icon: Icon(Icons.edit),
>               onPressed: onPressed,
>               tooltip: tooltip,
>             ),
>           ),
>         ],
>       ),
>     );
>   }
> ```

Thank you so much for this answer! I will close this now as this is a quality solution
