### ISSUE TITLE
Add onClicked/onOpen attribute for floating action button

### ISSUE THREAD

**Issue by jadenwjh** [marianocordoba/fab-circular-menu#16]
Currently I would like my other buttons to close when I click on the FABcircularMenu, but the widget lacks an attribute for me to have a callback, I cant do so :(

**Comment by jadenwjh** [comment]
Im referring to the menu itself, as Im aware that the children have an OnPress attribute already

**Comment by marianocordoba** [comment]
Hi! I'm not sure i understand what you are trying to do, but the widget does have a callback:

```
FabCircularMenu(
  onDisplayChange: (isOpen) {
    // Do something when the menu is opened / closed
  },
  children: <Widget>[
    // ...
  ],
  // ...
)
```

If this is not what you need, please explain a bit more and provide an example. Thank you!
