### ISSUE TITLE
FAB icon color

### ISSUE THREAD

**Issue by sunalive** [marianocordoba/fab-circular-menu#17]
There is no option to set/change the FAB icon color.  It defaults to black and no way to change it.

![image](https://user-images.githubusercontent.com/2279283/89002831-1a064000-d2cc-11ea-809b-93acacfa756e.png)

**Comment by marianocordoba** [comment]
Hi @sunalive!

You can use `fabOpenIcon` and `fabCloseIcon` properties. If you want to change the color of the icon, you can use an `Icon` widget and set the `color` property:

```
FabCircularMenu(
  children: [
    // ...
  ],
  fabOpenIcon: Icon(Icons.menu, color: Colors.white),
  fabCloseIcon: Icon(Icons.close, color: Colors.white)
)
```

I hope this works for you!

**Comment by sunalive** [comment]
Thanks. That worked!
