### ISSUE TITLE
Menu not auto close after clicked on menu item

### ISSUE THREAD

**Issue by chungbkhn** [marianocordoba/fab-circular-menu#4]
After clicked on one menu item, I want a solution to close menu by code but I can't found anyway to do it at the moment. This feature is quite comment, I think it should be an item in wishlist features :)
Thanks for your time.

**Comment by marianocordoba** [comment]
I will add a way to open/close the menu programmatically asap

**Comment by yelkamel** [comment]
Any news ? :)

**Comment by eliasjtg** [comment]
News?

**Comment by j574144** [comment]
Hi, thanks in advance, please add this feature according your available, but thinking on our nerve system 😂

**Comment by marianocordoba** [comment]
Hey! First of all, thanks for waiting. I've just added a `controller` property that takes a `FabCircularMenuController` which allows you to control the menu programatically. 


```
final controller = FabCircularMenuController();

FabCircularMenu(
  child: ...,
  controller: controller,
  options: <Widget>[
    IconButton(icon: Icon(Icons.widgets), onPressed: () {
      controller.isOpen = false;
    }, iconSize: 48.0, color: Colors.white),
    ...
  ],
 )
```

I will improve documentation and examples soon.
