### ISSUE TITLE
[Request] I wanna be change fab close button background color.

### ISSUE THREAD

**Issue by hukusuke1007** [marianocordoba/fab-circular-menu#6]
Hello.

I wanna be change fab close button background color. 
I do not find interface to change background color. 
Can you add "fabCloseColor" property ?

Best regards.

**Comment by jamesmenera** [comment]
@hukusuke1007 I opened up a [PR](https://github.com/marianocordoba/fab-circular-menu/pull/7l) with this feature. We will see if it gets merged in

**Comment by marianocordoba** [comment]
Added in #7
